//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int id { get; set; }
        public int fkevent { get; set; }
        public int fkuser { get; set; }
        public int fkstatus { get; set; }
    
        public virtual events events { get; set; }
        public virtual attendancestatus attendancestatus { get; set; }
        public virtual users users { get; set; }
    }
}
