//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_eventattendees
    {
        public int attendanceId { get; set; }
        public int eventId { get; set; }
        public Nullable<int> userId { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string displayname { get; set; }
        public Nullable<int> attendanceStatusId { get; set; }
        public string status { get; set; }
    }
}
